version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8001/api/v1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./data/trailtrack.db
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - FRONTEND_URL=http://localhost:3001
      - UPLOAD_DIR=/app/uploads
    restart: unless-stopped

volumes:
  data:
  uploads:
